router/config.go, router/handler_ctrl/bind.go, router/handler_ctrl/route.go, xgress/options.go, xgress/registry.go, xgress/xgress.go, xgress_proxy/factory.go, xgress_proxy/listener.go, xgress_proxy_udp/factory.go, xgress_proxy_udp/listener.go, xgress_transport/dialer.go, xgress_transport/factory.go, xgress_transport/listener.go, xgress_transport_udp/factory.go, xgress_transport_udp/listener.go
De-stutter Xgress API component names.
=> De-stuttered the Xgress API. (#40)

router/xlink_transport/config.go
Should hopefully fix the current smoke failure
=> Init xlink channel options to defaults if not specified

.gitignore
super small pr to add github_deploy_key to the .gitignore
=> update gitignore to add github_deploy_key

controller/db/terminator_store.go, controller/handler_ctrl/session_request.go, controller/network/network.go, controller/network/session.go, controller/network/terminator.go, controller/xt/xt.go, router/forwarder/forwarder.go, router/handler_ctrl/route.go, router/xgress/xgress.go, router/xgress_transport/dialer.go, router/xgress_transport_udp/dialer.go
- add xt.PeerData type
- convert all peer data maps to xt.PeerData
- allow xgress dials to return session runtime peer data
=> adds support for e2e via peer data for openziti/edge/issues#173

router/forwarder/forwarder.go, router/forwarder/options.go, router/handler_ctrl/bind.go, router/handler_ctrl/dial.go, router/handler_ctrl/pool.go, router/handler_ctrl/route.go, router/router.go
- adds worker pool support in routers for dial and route handers
- adds configuration for pool/queue under the forwarder section
=> fixes #109, adds pools of workers for select handlers

controller/controller.go, controller/handler_ctrl/accept.go, controller/network/circuit_test.go, controller/network/network.go, controller/network/path_test.go, controller/network/router.go, go.mod, go.sum, router/router.go, router/xlink_transport/listener.go
- Adds version header to outgoing controller hellos and incomming router
hellos
=> fixes #133

.gitignore, go.mod, go.sum, router/forwarder/forwarder.go
Purge session from forwardTable during unrouteTimeout if no xgressForSession is found
=> Eliminate memory leak (forwardTable concurrent-map)

go.mod, go.sum, router/xgress/options.go, router/xgress_transport/client.go, router/xgress_transport/dialer.go
Update foundation to `v0.15.24`, supporting timeout on dial.
=> Support Dial Timeout (primarily Xgress)

controller/network/network.go, controller/network/session.go
=> Parallel Network Re-route with Session Concurrency

router/forwarder/options.go
This setting probably doesn't do anything without this fix.
=> Fix for xgressDialQueueLength option in forwarder.options

controller/config.go, controller/db/db.go, controller/db/testing.go, go.mod, go.sum
Implement bbolt tracing with on/off switch.
=> bbolt Tracing

controller/controller.go, controller/xweb/config.go, controller/xweb/contextutil.go, controller/xweb/demux.go, controller/xweb/registry.go, controller/xweb/server.go, controller/xweb/web.go, go.mod, go.sum
See `web.go` for package doc.
- adds config structures
- adds server structures
- simplifies interfaces
- removed unused remnants
- refactor work
- adds doc
=> initial xweb implementation

controller/xweb/config.go, controller/xweb/contextutil.go, controller/xweb/demux.go, controller/xweb/registry.go, controller/xweb/server.go, controller/xweb/web.go
- fixes multi server startup would block on first server
- fixes comments, goland was complaining
- adds better output for what APIs are starting on what servers/bind
points
- adds IsHandled() demuxer
=> fixes xweb comments, fixes xweb startup

controller/api/responder.go
Setting the content-length header for HTTP responses allows the golang net/http library to avoid chunking the response.
=> sets content-length http response header

router/config.go
- internal configuration values are stripped before save
- adds method to create a backup of the current configuration
=> adds ability to update and save loaded configuration

controller/api/timeouts.go
Previous to this change, a panic at this level would result in a 200 OK being the default response. Would make tests pass erroneously and cause a tester to chase their tail.
=> adds a default panic 500 HTTP status code

router/forwarder/options.go
=> Update default xgress dial workers to 100 and link dial workers to 25.

controller/api_impl/management-api.go, controller/controller.go, go.mod, go.sum, health/handler.go, router/router.go
- xweb v2 uses different simpler names
- reduce xweb instances to a single instance in fabric
=> upgrades xweb to v2.0.0

controller/config.go, controller/controller.go, controller/db/base_store.go, controller/models/base_model.go, controller/network/network_test.go, controller/raft/member.go, controller/raft/mesh/mesh.go, controller/raft/mesh/mesh_test.go, controller/raft/raft.go
Add initial cluster events.
Simplify ctrl <-> ctrl connection.
Fix version mismatch detection
=> Miscellaneous raft related updates

controller/raft/raft.go, go.mod, go.sum, health/handler.go, router/config.go, router/router.go
- improve cluster bootstrap
- Add support for router link health check. Fixes #700
=> link health check
